os:
  - linux
dist: trusty

language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"

services:
  - docker

env:
  - DATABASE_URI=localhost

before_script:
  - sudo apt-get update
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
    wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
    wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda config --get channels
  - conda config --add channels conda-forge
  - conda config --add channels bioconda
  - conda config --add channels https://conda.anaconda.org/thoba
  - conda info -a
  - deps='pip pipenv click jinja2 tqdm py2neo=3.1.2 pyvcf=0.6.8'
  - conda install pip conda-build anaconda-client $deps
  - python setup.py install
  - git clone https://github.com/COMBAT-TB/neo4j_db.git && cd neo4j_db/
  - docker-compose up --build -d && cd ..
  - docker ps
  - sleep 30

script:
  - travis_wait 30 pytest -v test/
after_success:
  - test $TRAVIS_BRANCH = "master" && bash conda/conda_upload.sh
